sudo: false
env:
  global:
    - NODE_ENV=test
language: node_js
node_js:
  - "20.11.1"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
install:
  - npm install
script:
  - npm run test
after_success:
  - npm run coveralls