name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, closed]
  release:
    types: [published]

jobs:
  update-release-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: npm install

      - name: Run Audit-CI to check for vulnerabilities
        run: npm run audit-ci

      - name: Run tests
        run: npm build

      - name: Run tests
        run: npm test

      - name: Release Drafter
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PA_TOKEN }}
